name: randombytes
description: Function than generates random bytes at given length.
version: 0.1.0
homepage: https://github.com/xtyxtyx/randombytes
author: xuty <xty50337@hotmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
